### ISSUE TITLE
Media Gallery

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#101]
I am starting to write the User guide, and want to include images in the different documentations pages on the platform (User guide, terms of use, etc.), by hosting the images directly in the admin side (as opposed to using URL linking to images hosted elsewhere on the web).

Is it possible to create a media gallery in the admin side, where I would upload the pictures, and link to them when writing the pages in HTML?

**Comment by ricardogsilva** [comment]
There are some open source django gallery apps out there that we could integrate. IMHO this would be preferable to  rolling up a custom solution.

Looking around for a an appropriate candidate, it seems we could integrate the [django-photologue](https://github.com/jdriscoll/django-photologue) app.

This app seems suitable since it:

- seems to be able to deliver the expected result (upload photos via admin and allow one to store, visualize and retrieve them);
- has good [documentation](https://django-photologue.readthedocs.io/en/stable/index.html);
- is actively developed;
- is well ranked on [django packages](https://djangopackages.org/grids/g/gallery/);
- has a [demo site](http://www.django-photologue.net/) up that showcases its features;

Based on the supplied documentation and demo my estimate is that it should be possible to integrate this into the WINS platform in with two days of work.

@simboss @afabiani what is your opinion?

**Comment by ricardogsilva** [comment]
After some internal discussion, this is the proposed work and implementation plan:

## proposal

Integrate django-photologue with geonode


### Overview
django-photologue provides an image management and gallery application for 
Django. 

Out of the box it allows an admin to upload images, set them to either 
public or private (this only affects the web viewer, image URL is still 
public) and create galleries. It also features some views for displaying
images and galleries.

These features seem to match the current requirements from the client.


### Implementation

The integration process will involve the following:

- [ ] Install django-photologue (along with its dependencies);
- [ ] Sync the database;
- [ ] Add django-photologue to the `INSTALLED_APPS` setting;
- [ ] Add its urls to the main `urls.py` file;
- [ ] Customize the templates in order to give them a more familiar look
- [ ] Extend photologue's current admin section in order to display the 
  URL of an uploaded image directly in its `change_list.html` page

**Comment by afabiani** [comment]
@meyerch  in order to test this, as an "Admin" go to 

http://ihp-wins-dev.geo-solutions.it/admin/photologue/photo/

add your images and you will get something like this

![image](https://user-images.githubusercontent.com/1278021/35146169-702f40c0-fd0a-11e7-8688-7bcf95abe1f2.png)

The "Photo url" can be used on HTML templates and documents as IMG SRC

<img src="http://ihp-wins-dev.geo-solutions.it/uploaded/photologue/photos/unesco_ihp_en_transparent.png" />

Absolute URL:
```
<img src="http://ihp-wins-dev.geo-solutions.it/uploaded/photologue/photos/unesco_ihp_en_transparent.png" />
```

or Relative URL (to the server):
```
<img src="/uploaded/photologue/photos/unesco_ihp_en_transparent.png" />
```

Remember that a photo must be public in order to be visible outside.

**Comment by meyerch** [comment]
Many thanks, this is exactly what we needed. 

One question before archiving this task: I notice that there is a "Photo effect" option. From what I understand, admin can define a template photo effect and apply it to any photo when adding them in the "Photos". 
Now, there is also a "Photo size" menu. Again, I understand that I can define a template size. However, when I add a photo, I don't have the option to chose a predefined size like with the "Photo effect" menu. 
So my question is: is it normal not to be able to apply a predefined size when adding a photo? If yes, can you explain what is the "Photo size" menu for? Thank you.

**Comment by afabiani** [comment]
Hi @meyerch 
that option is useful if you want to currently expose the photo galleries outside by using that plugin functionality.

The tool we installed allows you to create pages with thumbnails and pictures previews like a blog.

In this case we are using it a bit differently, more like a storage for pictures, and therefore those options are not useful when linking the images directly as img src instead of using Python code.

**Comment by meyerch** [comment]
Hi, 
Thanks for the answer. 
For now, we are fine with the gallery as is.

**Comment by meyerch** [comment]
accepted and closed. THanks
