### ISSUE TITLE
Automatically generates the user name based on the first name and last name

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#11]
"UNESCO-GeoNode-Refactor-2017-Timeline" 'PHASE I'!N7

PROBLEM: I have just registered with the following name : "Chlo2 meyer^$" and the username created is "chlo2.meyer" (see list of users in the admin interface). So, I face 2 problems here: 
        - Can you make sure that numbers are not accepted in the username? 
        - When registering, I was not warned that the characters I entered were not valid (I typed "Chlo2 meyer^$ and sent the request successfully. It is only when I checked on the admin interface that I noticed some characters had been deleted). Can you make sure that the person who is registering is warned when the name entered is not valid and have to change it to be able to send the registration form? 
See 2 screenshots of what we have in mind on the left. Ours could say "Enter a valid name. You can only use unaccented letters and dash ('-')" For now, we only get a warning message when a field is left empty or when the email is not valid (which the 2nd screenshot shows)

Other question: once the administrator has accepted the registration of the person, is the person receiving an email confirming his/her registration and the username and password ?

**Comment by mekanix** [comment]
Answer to last question is that we can send username, but not the password as it's already encrypted at the moment of accepting the registration

**Comment by meyerch** [comment]
There is still an issue with the generation of username : dash are not accepted. 
I registerd as "Hello-Oo Test-Test", and the username generated is "hellooo.testtest". Even in the personnal info, the dasg has disappeared. Can you make sure that dashes are accepted?

![username.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fd879f318c82a48aabf301b44fff9e2c4533317346f6727181b77deb447d005a5d4bfa41585c44f8f9882ea0b42e6c981e5ab38532022d8c6853beb2901eb80bbb258b4885b5b98945c6ec3924f5c6.PNG)

**Comment by meyerch** [comment]
There is another issue: 
2 persons can register with the same username (as experienced by myself). This result in the impossibility to connect (for both the users) to the platform later on, as the system retrieves 2 profiles at the same time. 

When a person registers, is there a way for the system to signal that another user already has that name, hence the registering user must change her/his name? If the registering user does not alter his name, then registration should be blocked to avoid the creation of a 2nd profile with the same username.  

I am suggesting this solution because we prohibited registering users to use numbers in their name.. Or can we prohibit number in the name/surname of the registration form, but allow the system to add a number at the end of the username when it has identified that it is the 2nd user with this username?

Or do you have other ideas on this? Thanks!

**Comment by afabiani** [comment]
Now accepting also dashes

**Comment by meyerch** [comment]
Perfect, thanks!
ACCEPTED
