### ISSUE TITLE
For a person to register, she has to accept the ToU, otherwise, she cannot register to WINS.

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#12]
This is something we already discussed together, but we realized it was missing in the table.

What we want is to force users to accept the ToU, otherwise, they should not be able to register. What we have in mind is to add a tick box and a sentence at the end of the "Register" form, before the "Sign up" button. The sentence would say 'I agree to the IHP-WINS Terms of Use" , where 'Terms of Use' would link to http://ihp-wins-dev.geo-solutions.it/uploaded/terms-of-use/ToU_IHP-WINS_30august17.pdf . 
Would-be users should not be able to sign up if the box is not ticked. If it is not ticked and registrating person tries to sign up, a red message under the ToU field should appear, stating "You may not register unless you agree to our Terms of Use".

**Comment by afabiani** [comment]
Missing mandatory checkbox on registration form

**Comment by meyerch** [comment]
In the French version, please change "* Avant de commencer à utiliser ce service, vous devez soigneusement lu et j’accepte les Conditions d’utilisation" 
for "* Avant de commencer à utiliser ce service, vous devez avoir soigneusement lu et accepté  les Conditions d’utilisation"

Regarding the ToU page, for now  it opens up in a .pdf page (http://ihp-wins-dev.geo-solutions.it/uploaded/terms-of-use/ToU_IHP-WINS_30august17.pdf).
Instead of opening on a .pdf page, we would like the ToU to open up on a proper WINS page, just like the About Us page but specifically for the ToU.

**Comment by afabiani** [comment]
Can be set by "admin" from

http://ihp-wins-dev.geo-solutions.it/admin/content/termsofuse/1/

**Comment by meyerch** [comment]
ACCEPTED
