### ISSUE TITLE
Group Activity List malfunctions

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#15]
"UNESCO-GeoNode-Refactor-2017-Timeline" PHASE 1![N:12]

[AF] - Currently are displayed Groups the user is member of and Groups that are Public. We can modify this behavior of course. --> One question for clarification regarding the groups that are public (and thus displayed in the list in the metadata): does "public" include groups that are "public (invite only)" (i.e. Any registered user can view the group. Only invited users can join), or just the groups that are "public" (i.e. Any registered user can view and join a public group)? 
After testing it, it seems that it is the first option (public include all public groups, whether they are on invitation or not). In that case, we would like to change it, for the "group" list in the metadata to only display Groups the user is member of and Groups that are public (i.e. groups that any registered user can view and join). 

+ can you make sure that the "Group" shows in the "Info" tab under the viewer? Just like Title, Abstract, etc. are shown. "Group" could go under "Responsible"

[AF] - OK --> OK it is displayed, but is it possible to display the group name and not the group slug? For exemple, for this layer http://ihp-wins-dev.geo-solutions.it/layers/geonode:arab_states_region, "IHPChairs" is the slug for the group called UNESCO-IHP Chairs. We would prefer the latter to be displayed. When choosing the Group in the metadata, the slugs and not the proper group names are displayed in the list.

**Comment by meyerch** [comment]
Additionally, a problem that was previously solved has reappeared. 

In the "Group" field when editing the metadata (both in the 'Wizard' and the 'Advanced edit'), all the groups are now listed. Which means that user can associate their layer/doc/map to a group he/she is not even a member of. 

Can you make sure that only the groups that the user is a member of show up in the "Group" menu when editing metadata?

**Comment by afabiani** [comment]
Hi Chloe,
is this occurring with standard users also? Currently the logic should be the following:

- If you are Admin or Staff you should be able to see all the groups
- if you are a standard user you should be able your Groups plus the "Public" ones

I will test it again now. In the meantime can you please confirm that the workflow is correct? Also, in case of a Group Manager, it should behave like a standard user or like a Staff member?

**Comment by meyerch** [comment]
Hi, 
Sorry I forgot that public groups also show up in the list.
Then let me run some tests and I will come back to you to confirm  that it works.

Regarding your questions:  Yes, he workflow is perfect. 
And for a Group manager, it should behave like a standard user. Only Admin and Staff should be able to access all the groups in the list.

**Comment by afabiani** [comment]
Ok, in that case I have to revise Group Managers which now should behave similar to Staff members.
Will test it again ASAP. Thanks for your feedbacks.

**Comment by afabiani** [comment]
Just pushed a minor improvements which should:

- Improve checks on current user group membership

- Remove duplicates (if any) from the list

**Comment by meyerch** [comment]
Hi, 
After a few tests, my conclusion is that in the 'Group' field of the metadata, the groups that show up are the "Public" and "Public (invite only)" groups. 
Can you make sure that only the "Public" groups + the Groups that the user is a member of show in the list? I.e. groups that are "Public (invite-only)" should not be displayed (unless the user is a member of some of them of course).
Thanks

**Comment by meyerch** [comment]
Also, there is still the issue mentionned in the very 1st comment on this thread, which is that in the "Group" field of the metadata, it's not the actual name of the group which is displayed, but rather the slug (see screenshot below). 
Can you make sure the actual name is displayed? Because the slug does not allow for space or anythin, so it is not always understandable.

![slug-group.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb988f24cf84bb80fcaf01e81fe086264c22703d46f96925dce22ceb172f07090e4bae440e5f44fff98d2ba7b33a72984019af80330b2b9b645bf9fa9015ad00b32a8a4a85beb5884cc1ec3821e68f9d02.PNG)

**Comment by afabiani** [comment]
Ok

**Comment by afabiani** [comment]
Done.

**Comment by meyerch** [comment]
Perfect. 
ACCEPTED

**Comment by meyerch** [comment]
I am reopening this issue since I noted something: 
In the "Info" tab (layer, doc, map), it is still the group slu that appears, and not the actual group name. Can yo umake sure it is the group name that shows up here. (see screenshot below)
![group-slug](https://user-images.githubusercontent.com/32269305/32109865-3c36e522-bb36-11e7-9ce0-81b694b39b36.PNG)

Also, in the "Metadata details", the "Group" field in no longer appearing under the 'Indentification' section. Can you make sure the "group" field is displayed and shows the group name? 
![group-metadata](https://user-images.githubusercontent.com/32269305/32109939-7878ded2-bb36-11e7-9a82-c4c8932600e6.PNG)

Thanks

**Comment by afabiani** [comment]
Sure

**Comment by afabiani** [comment]
Done. I have update the "metadata details" also. Please take a look if it's ok with you.

**Comment by meyerch** [comment]
Perfect.
I archive this task
