### ISSUE TITLE
Add the WINS logo in the viewer

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#17]
"UNESCO-GeoNode-Refactor-2017-Timeline" PHASE I![N:26]

We now have an official logo for WINS, and we would like it to slightly change the logos that are displayer in the viewer of the layers/maps and on the maps when they are printed. What we want is the UNESCO-IHP logo + the WINS logo. See screenshot in N45

**Comment by meyerch** [comment]
See the screenshot below for what we have in mind: in the upper right corner, UNESCO-IHP logo and then WINS logo (just as it is in the header)
I believe you already have the logos needed. Otherwise, let me know  and I will send them to you.

![logos_viewer.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e49b9d2c91bcbf86eca846b61fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8228b4584b3bc824ec4e03d22e3898c4b2c53.PNG)

**Comment by afabiani** [comment]
![image](https://user-images.githubusercontent.com/1278021/31721793-aa62fbd0-b41a-11e7-8040-710bf7eec70a.png)

**Comment by meyerch** [comment]
Thanks. Logos are perfect. 

Can you just delete the "UNESCO-IHP Wins" link that is right below the logos (highlighted in yellow in the screenshot below)?

![logo-viewer.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e49b9d2ccf95a08afeba51e611b2843b492d762a10e17132d0ba29bb162e5509091fa9435d0944fcfa892fa6b73976884e17ff933c0120996048e6edc00db513bb27814e80b6b48e4cc2ec3b2ce083875d73.PNG)

**Comment by afabiani** [comment]
Done.

**Comment by meyerch** [comment]
Accepted
