### ISSUE TITLE
Upgrade to GeoNode 3 and removal of custom UNESCO GeoNode branch

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#181]
In view of the UNESCO developments (new end-user frontend, new generic functionalities) it is worth migrating to GeoNode 3, to avoid losing these improvements inside version 2.
We need to:

 - investigate the effort to upgrade the custom WINS project to GeoNode 3
 - investigate if we can get rid of the custom upstream GeoNode version (currently [unesco_ihp_2.10.2](https://github.com/geosolutions-it/geonode/tree/unesco_ihp_2.10.2) branch).

The latter point is of primary importance to simplify the maintanance, and avoiding to work on both a geonode project (unesco-ihp) and a custom geonode branch for the same application.
Regarding this the following points need to be reviewed:

- what are the customizations inside the UNESCO GeoNode branch?
- do we have customizations that CAN'T be ported to the downstream unesco-ihp project? In that case can we hypothesize some developments on GeoNode that would permit it?
- do we have customizations that CAN be ported to unesco-ihp right away? In that case let's estimate the effort.

**Let's list the above customizations inside the comments to this epic**

**Comment by giohappy** [comment]
From a quick look to the [diff between branch 2.10.2 and unesco_ihp_2.10.2](https://drive.google.com/open?id=1UFb52LMwRzVJ98KJ9fKHuCH50CNxNo9z) the main differences are:

 - some differences in deps versions
 - custom user fields
 - IHPNotificationsHookSet
 - templates
 - some modification to the resources API
 - use of polymorphic_ctype__model (don't know why)

with some work I guess nothing impossible to be ported to the unesco-ihp project.

**Comment by afabiani** [comment]
@giohappy about the topic of getting rid of a customized GeoNode 2.10.x and use the default one, from what I can see here 

https://github.com/GeoNode/geonode/compare/2.10.x...geosolutions-it:unesco_ihp_2.10.2?expand=1

probably the most difficult part would be adding the "doi" filed to the ResourceBase. All the rest seems to be relatively easy to port to unesco_ihp.

I remember in the past we tried to hook the ResourceBase at initialization time. I tested this approach recently (only with Django 1.11.29) and it does not seem to work correctly anymore. Or, to be more precise, the field is created dynamically but the LayerForm does not recognize it when saving the metadata. This needs further investigation.

Other than this, I guess all the other changes can be easily ported to the geonode-project instance.

**Comment by afabiani** [comment]
@giohappy upgrading to GeoNode 3, at least the version currently available on master (I'm not considering bugs and regressions introduced here, just a blind upgrade of the framework), shouldn't be too hard to achieve.

As an experiment, I created a "my_geonode" project, based on GeoNode 2.10.x, and populated the database through the migrations.

I then updated the environment and the dependencies. After making a few adjustments to pavements and settings files in order to be Py3 compliant, I have run the migrations again.

For the time being, I had no conflicts and the project was successfully converted to a GeoNode 3 one.

Of course, this was an almost empty project and with no further customizations. But in any case, the "unesco_ihp" one shouldn't be too hard to migrate (at least the database).

By considering also a full backport of the UNESCO functionalities and testing a complete backport could require between 3 and 8 days (in the worst case) IMHO.

**Comment by giohappy** [comment]
@afabiani  wrt to the doi field, what if we propose to adopt it officially upstream? It's generic and might be useful to others.

**Comment by giohappy** [comment]
@afabiani  wrt to the doi field, what if we propose to adopt it officially upstream? It's generic and might be useful to others.

**Comment by giohappy** [comment]
I've opened an epic to make a granular analysis of the tasks and set estimates.
https://github.com/geosolutions-it/unesco-ihp/issues/183
