### ISSUE TITLE
Rework on the homepage to embellish it and make it more appealing

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#20]
Check screenshots and material provided by Chloe

**Comment by meyerch** [comment]
Regarding the design of the platform, we have 3 comments below:

**Comment by meyerch** [comment]
1. Make sure that the IHP-WINS logo in the header is clear. Fo rnow, it looks blurry
![header-logo-blurry.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e0919b278791e483e6b84ce95ffc813b543e316546b3397f8fe62bab0021435a561ff8455d5b12aaa88c29a3e03c70895c0fedd0685976d42103eee9dc4be05ce36ade0d97bcae8b45cae93825e08d8d4c3819051081f74f78.PNG)

**Comment by meyerch** [comment]
2. In the footer, please use the logo I just sent to Alessio instead. This logo is a bit lighter and will contrast more on the footer, for better visual results.

**Comment by meyerch** [comment]
3. Regarding the 'About us page' (http://ihp-wins-dev.geo-solutions.it/about-us) and the 'Terms of Use' page (http://ihp-wins-dev.geo-solutions.it/terms-of-use), please remove the image on the left of the page. 

We like the idea of having this image, but for now, the outcome is not optimal: when changing page resolution, the image moves up on top of the text, which is not ideal (see screenshots below).

Since this is not a priority for now, we ask you to remove the image for now. 
Later on, we will see how we can make the result better, when priorities will have been tackled.
![image-overlaying-text.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e1999b2487cea699ecad4fa544f99a2e0b33763110e1673295f127b54778154d555ca948090b40f9fddf7df7b33e75dc5c0beed1695f75c33b13bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8f48381c011f8afa5d32a48b06.PNG)

**Comment by afabiani** [comment]
Done. Remember to clean up the browser cache in order to reload the images.

**Comment by meyerch** [comment]
accepted
