### ISSUE TITLE
Error with password reset link

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#279]
![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/fc179db0-1872-4a18-9e84-6ea479d7d3c0)

**Comment by afabiani** [comment]
Unfortunately, this is an error on `django-allauth` module

https://github.com/pennersr/django-allauth/issues/2536

I temporarily patched it in order to make it working again. For the long term solution we need to wait for the fix into the official distribution.

Alternatively, we should rewrite the `IHPProfile` currently inheriting from the GeoNode one

https://github.com/geosolutions-it/unesco-ihp/blob/dev/ihp/people/models.py#L81

in order to implement directly the User abstract class. This could impact a lot on the code and it could also lead to other issues.

**Comment by giohappy** [comment]
can't we revert to a previous version of django-allauth where it worked? I don't think we have made significative changes to its integration.

This problem will also impact GeoNode 3, won't it @afabiani ?

Anyway, where did you apply the patch? Upstream or here?

**Comment by afabiani** [comment]
@giohappy it is not a `allauth` version issue and even not a GeoNode one. The problem is that we re-defined a custom IHPProfile which inherits the GeoNode one in order to avoid to monkey patch the latter.

Unesco needs some additional fields into the profile that are not included into the original GeoNode User model.

So, long story short, this issue happened only on unesco-ihp project and because allauth has a syntax error on one of its utility classes.

Currently I patched directly the allauth dependency on the IHP-DEV server

`/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/allauth/account/utils.py`

**Comment by giohappy** [comment]
Well, you see @afabiani that such a patch can't be maintained in that location.
I'd prefer remove the allauth dependency, copy allauth inside the ihp-wins repo, as a local django app, and apply the patch there with a **BIG BOLD COMMENT** explaining the reason we did this.

In the future we might revert to proper dependency if this is fixed upstream.

**Comment by afabiani** [comment]
@giohappy 

I forked the repo on geosolutions.it and applied the patch

https://github.com/geosolutions-it/django-allauth/commit/df2f0cdf145b92bf89f7c0664d1cdf152fbe1e5c

moreover I updated the requirements.txt inorder to match the new dependencies

https://github.com/geosolutions-it/unesco-ihp/pull/283/files

**Comment by giohappy** [comment]
fixed in geosolutions-it/django-allauth@df2f0cd
