### ISSUE TITLE
Non admin user cannot change permission on resources

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/unesco-ihp#345]
Non admin users can not change permissions on documents, only admins can.
Apparently the "Change permissions" button is not shown even if the user is the owner of the resource.

We shall investigate further to make sure this is a bug.

**Comment by afabiani** [comment]
Currently the behavior is coherent with the other resources workflow, Layers and Maps.

As per @giohappy comments, we will probably need to remove the `Change Permissions` form the upload form too in order to make everything consistent.

**Comment by giohappy** [comment]
@afabiani if we have integrated the changes we did recently to the advanced workflow only partially, of course we need to complete them and remove the `Change Permissions` upstream. Please open an issue and make the PR upstream.

**Comment by afabiani** [comment]
@giohappy ok, will put here the reference ASAP

**Comment by afabiani** [comment]
@giohappy please see the issue [here](https://github.com/GeoNode/geonode/issues/7135)

**Comment by giohappy** [comment]
please @afabiani let's complete this thing. Let's remove the permissions panels from the upload templates in GeoNode if the advanced workflow is active.

**Comment by simboss** [comment]
@afabiani once you have commited the fix for removing permission from the upload templates, please indicate also how to patch the PROD instance.

**Comment by afabiani** [comment]
@giohappy @simboss the PR is available [here](https://github.com/GeoNode/geonode/pull/7151)
It requested a bit more than expected because while developing I have found a mistake in the permissions logic which was triggered twice during the upload. This mistake impacted the current code because by removing the permissions form during the upload phase, we ended up with an incomplete layer configured on GeoServer.

In order to apply the fix to UNESCO project we will need to proceed as follows:

1. Backport the fix to GeoNode branch 3.2.x
2. Apply the fix to `/home/geosolutions/work/repo/geonode` (I would suggest to tag the UNESCO GeoNode version here in order to be sure we do not introduce other issues)
3. Restart `UWSGI` and `supervisor`

Notice that there's no need to touch the `unesco_ihp` GeoNode project in this case, since for this functionalities it completely relies on GeoNode.

**Comment by simboss** [comment]
@afabiani once this is merge, please, do the backport (point 1).

About point 2, please, clarify what needs to be done, i.e. what "Apply the fix ..." means.

**Comment by afabiani** [comment]
@simboss my suggestion is to minimize the impact by:

1. tag/branch the current GeoNode commit used by UNESCO

```
commit c1712aeb91c037f12e3054419c0e447c32ab300a
Author: Alessio Fabiani <alessio.fabiani@geo-solutions.it>
Date:   Fri Mar 12 18:25:53 2021 +0100
```

2. cherrypick the backported PR
3. pull the commit and restart UWSGI and supervisor

**Comment by simboss** [comment]
@afabiani I will ping you tomorrow about this.

**Comment by simboss** [comment]
@afabiani go ahead with 1. and 2.

The instance does no use docker so when the Unesco project and the unesco GeoNode branch is ready we can update prod.

**Comment by simboss** [comment]
@afabiani please, document the branching and building [here](https://docs.google.com/document/d/1RAnAsywPRgZrsICF5qgSVsDbQTbbftotsSrG7paUx-4/edit).

Let me know when you are done.

**Comment by afabiani** [comment]
@simboss deployment done, now a standard user won't see che perms form anymore when the advanced workflow is enabled
![image](https://user-images.githubusercontent.com/1278021/112473804-1a79ac80-8d6f-11eb-976f-18fc5c0fa447.png)

The library thumbnails have been also regenerated
