### ISSUE TITLE
Layers, Maps, Documents very slow at generating pages

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/unesco-ihp#347]
Layers, Pages, Documents on IHP WINS are all very slow when paging over.

We need to investigate and understand why this is happening.
Then we shall propose a plan ti ix this with an estimate.

**Comment by afabiani** [comment]
@simboss @giohappy after having investigated this issue I realized where the culprit is for this odd slowness should be.

First of all, this happens only when the full advanced workflow is enabled and the user are not "superusers", like in the IHP-WINS use case.

In particular, the part of security code which is activated by this specific use case is the following one

https://github.com/GeoNode/geonode/blob/master/geonode/security/utils.py#L108

As you might notice from the code, that check is quite inefficient since it is a loop across all the resources. Moreover, the apis that build the resource counters call this snippet of code for every single group, category, groupCategory or keyword. Therefore the slowness is exponential.

Now, first of all this code must be optimized by removing the sequential loop and making the DB performing the filtering.
This should be sufficient already. I did some tests locally by trying to replicate the IHP-WINS db and I notices a huge improvement, several orders of magnitude.

The fix proposed is immediate and will impact the whole GeoNode performance, since this method is used in different parts of the code. It will take less than 0.5 hours.

If we would like to do something much more complex, we should envisage a smart caching mechanism allowing us to avoid computing the counters every time. This further option is much more complex and requires several days to be correctly and efficiently implemented.

My opinion, however, is that allowing the DB indexes to perform the checks will be more than enough for our purposes, without the need for a caching mechanism.

**Comment by afabiani** [comment]
Here is the patch to apply

```diff
diff --git a/geonode/api/resourcebase_api.py b/geonode/api/resourcebase_api.py
index 3e72c84..821c302 100644
--- a/geonode/api/resourcebase_api.py
+++ b/geonode/api/resourcebase_api.py
@@ -225,12 +225,6 @@ class CommonModelApi(ModelResource):
         else:
             filtered = semi_filtered
 
-        if settings.RESOURCE_PUBLISHING or settings.ADMIN_MODERATE_UPLOADS:
-            filtered = self.filter_published(filtered, request)
-
-        if settings.GROUP_PRIVATE_RESOURCES:
-            filtered = self.filter_group(filtered, request)
-
         if extent:
             filtered = filter_bbox(filtered, extent)
 
@@ -245,26 +239,16 @@ class CommonModelApi(ModelResource):
                     Q(owner__username__iexact=str(user))))
             else:
                 filtered = filtered.exclude(Q(dirty_state=True))
-        return filtered
 
-    def filter_published(self, queryset, request):
-        filter_set = get_visible_resources(
-            queryset,
+        filtered = get_visible_resources(
+            filtered,
             request.user if request else None,
             request=request,
             admin_approval_required=settings.ADMIN_MODERATE_UPLOADS,
-            unpublished_not_visible=settings.RESOURCE_PUBLISHING)
-
-        return filter_set
-
-    def filter_group(self, queryset, request):
-        filter_set = get_visible_resources(
-            queryset,
-            request.user if request else None,
-            request=request,
+            unpublished_not_visible=settings.RESOURCE_PUBLISHING,
             private_groups_not_visibile=settings.GROUP_PRIVATE_RESOURCES)
 
-        return filter_set
+        return filtered
 
     def filter_h_keywords(self, queryset, keywords):
         treeqs = HierarchicalKeyword.objects.none()
diff --git a/geonode/security/utils.py b/geonode/security/utils.py
index 3807250..6b0d820 100644
--- a/geonode/security/utils.py
+++ b/geonode/security/utils.py
@@ -106,16 +106,19 @@ def get_visible_resources(queryset,
             filter_set = filter_set.exclude(Q(dirty_state=True))
 
         if admin_approval_required or unpublished_not_visible or private_groups_not_visibile:
-            _allowed_resources = []
-            for _obj in filter_set.all():
-                try:
-                    resource = _obj.get_self_resource()
-                    if user.has_perm('base.view_resourcebase', resource) or \
-                    user.has_perm('view_resourcebase', resource):
-                        _allowed_resources.append(resource.id)
-                except (PermissionDenied, Exception) as e:
-                    logger.debug(e)
-            return filter_set.filter(id__in=_allowed_resources)
+            from guardian.shortcuts import get_objects_for_user
+            _allowed_resources = get_objects_for_user(user, 'base.view_resourcebase')
+            # _allowed_resources = []
+            # for _obj in filter_set.all():
+            #     try:
+            #         resource = _obj.get_self_resource()
+            #         if user.has_perm('base.view_resourcebase', resource) or \
+            #         user.has_perm('view_resourcebase', resource):
+            #             _allowed_resources.append(resource.id)
+            #     except (PermissionDenied, Exception) as e:
+            #         logger.debug(e)
+            # return filter_set.filter(id__in=_allowed_resources)
+            return filter_set.filter(id__in=_allowed_resources.values('id'))
 
     return filter_set
 
```

**Comment by giohappy** [comment]
While designing [this proposal](https://github.com/geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV/issues/188#issuecomment-804788836) I noticed that, and I was going to propose to change it. So good to go @afabiani!

**Comment by afabiani** [comment]
PR available on GeoNode [here](https://github.com/GeoNode/geonode/pull/7174)

I propose to backport to IHP-WINS geonode branch and apply it as we already did for the admin perms before.

**Comment by simboss** [comment]
@afabiani thx.

About the PR, please, try to add some sort of tests just in case a regression of some sort pops up if someone touches this code in the future.

About the patch, let's wait for this to be in the GeoNode demo then we backport to UNESCO.

**Comment by afabiani** [comment]
@simboss there are a lot of tests already for the advanced workflow, we added a lot in the feature. I can add another one but most probably would be redundant. However ok.

About the second point, master demo won't be affected at all by this change since the advanced workflow is not enabled there.

**Comment by simboss** [comment]
@afabiani I understand there are tests already but how do we make sure a change to the code will not bring this sloweness back if we don't try to capture it somehow?

About the second point, I know that the validation workflow is not enabled on demo but, ideally this code should be tested a little further before installing it. In the end, they did not request this so we are not in a rush.

**Comment by afabiani** [comment]
I agree about the tests, I added some other specific ones. The existing ones guarantee that the code does not break the advanced workflow logic.

Let me know how you want to proceed with live testing and deployment.
