### ISSUE TITLE
WP7 [B25] - Autre -  Support WFS/WMS, to link WINS with other platforms

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#49]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Develop WINS to include WFS/WMS, to link WINS with other platforms

**Comment by afabiani** [comment]
I need more details on the expected results/workflow.

**Comment by meyerch** [comment]
We want other databases to be able to share their information on WINS through WFS/WMS, 
and conversely, we want to allow partener websites to be allow to display on their website information that is available on WINS.

Is it possible that a layer located on a database XXX appears in the WINS "layers" list through WFS/WMS? Or does the layer will only be available for retrieving once on the "map" creating page?

**Comment by meyerch** [comment]
As what is shown on http://www.geoportal.org/ , we would users to be able to search through wins and retrieve layers of our partners that are made available through WMS/WFS, to put them on maps and superimpose them with any other information stored on WINS.

**Comment by simboss** [comment]
The idea is to build on the [Remote Services](https://github.com/GeoNode/geonode/issues/1330) functionality that is currently present in GeoNode (and apparently is not documented).

The newly imported layers 

There is a number of issues with the implementation which we want to improve/fix; not everything can be done within the scope of this work but here is a list of priorities:

- [ ] support import of WMS layers (Higher Priority)
- [ ] improve the import process to give more feedback of the ongoing progress
- [ ] allow user to decide which layers to import from a remote service
- [ ] make sure layers are not imported before the final approval from the user
- [ ] provide mass removal of layers imported from a service
- [ ] support import of WFS layers (Lower Priority). This is not working properly ATM and it couldneed a complete rework since, looking at the code it is making a number of assumptions on the remote WFS which are not generic enough.

**Comment by simboss** [comment]
Please, see my comment above.

There is an hidden exeperimental functionality that we can use in order to support the import of remote WMS layers.  WFS is working

**Comment by meyerch** [comment]
Thank you. I will look at it and discuss with Youssef, and come back to you on this next week.

**Comment by ricardogsilva** [comment]
The current task seems a good fit for the existing `remote services` geonode functionality, which would be enhanced to provide a better user experience. For now we could focus on the whole register/import layers workflow. It seems that the following would be desirable:

1. Lighten the act of service registration:

    1. Collect name, URL and service type from user input (later we could also allow specifying authentication options, for enabling access to authenticated services)
    1. Do a basic capabilities check (without retrieving layers) to check whether the URL is valid and fill up basic service metadata, saving the service as a geonode resource

    Registering a new service won't import any layers by default, this will be explicitly requested by the user after the service has been saved

   This should be a lightweight process and can be made in a synchronous way

1. Add a new explicit *import layers from remote service* flow

   1. `service details` page will be enhanced with a `scan service layers` button - This operation will be available only to the service's owner

    1. This page will also feature the `last scanned` information, so that the user is able to see when the last sync with the external service was and decide if a new sync is in order (as there might be new layers to import)

    1. Scanning for layers consists in performing a full capabilities request in order to get the complete (potentially big) list of layers that are on offer

    1. After the service is scanned, the user is presented with a list of all available layers. The user will then be able to select which layer(s) should be imported

    1. The server does not need to store the full list of available layers, just the ones the user is interested on.

    1. Layer import will be an asynchronous process, where each import operation will be queued and processed when the server can spare the resources for it. As such there must be a mechanism to inform the user on the state of the import process.

    1. For each layer that the user chooses to import, a new database record is created. This record will be stored in a table that  features `status` and `details` fields. The status is (asynchronously) updated by the importer process in such a way as to transition between the following states: 

       *queued -> importing -> imported (or failed)*

       There is an additional field that records when the layer was last imported. The details field will record any details regarding the import process, such as any errors. This information is shown to the user in the `service details` page, where there is a *layers* section that shows a layer's name, its description, import status and import details.

   1. When a layer is done being imported it becomes available to be used in the other sections of geonode. the user receives an in-platform  message informing of the layer's availability. The `service details` page is also updated with a hyperlink to the newly imported layer details

   1. Each layer present in the service details page will also feature a `re-import` button in order to allow the user to retry the act of importing a layer

**Comment by meyerch** [comment]
Dear both, 

THank you for your work on this. For tests purposes, I added http://ows.mundialis.de/services/service  to the list of remote services, and was able to import 4 layers from there. 

I have some questions: 
- when registering a new service, only Web Map Service is available from the list. How to register WFS services? 
- when WMS layers are made available on WINS, is the legend supposed to appear automatically? When I imported this layer http://ihp-wins-dev.geo-solutions.it/layers/OSM-WMS, the legend was showing on the right side of the page. Now, when I go back to it, the legend is no longer displayed. Is it normal?  However, when creating a map, the legend is correctly displayed (see screenshots below: 1st the layer page with no legend; 2nd the map with the legend)
![wms_NOlegend_layer.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ff99891cacaca58aeeba4da062fc95304335316546b3397f8fe62bab0021435a561ff8455d5b12aaa88c29a3e03c70895c0fedd0685976d42103eee9dc4be05ce36ade0d97bcae8b4bcae93827e68e8a49391a0c1b80f74f78.PNG)

![wms_legend_map.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ff99891c8e86ae8ae7bb7ca95ce0d665043761260ea62864c7b96aea1b7a055b5a4afa17095a46f9af892ba5b638708b590defc3714d36976345f3e5db55ea43a82a994e8cbcbd8f4ec1ed3823e08c874c3b191755.PNG)

- when printing the map, the WMS disappears from the end PDF. Is it normal? It seems to act like some of the background layers that we cannot print.
![wms_print_disappeared.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ff99891c9291a081fd8047ad4ef184394326612c00e1673295f127b54778154d555ca948090b40f9fddf7df7b33e75dc5c0beed1695f75c33b13bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8d4e3b1b03118ffa5b36a98b06.PNG)

Thank you.

**Comment by meyerch** [comment]
Dear Giovanni, 
Thank for your comment. 

Below are answers/comments for some of your points + questions : 

- In some cases, we will actually need to store donwload and store data of our Member States on the paltform. Hence the need for WFS , in addition to WMS for display  only. 
- As for WMS URLs being available through WINS: I am not sure to understand this point. If we share this link with a partner, can the partner 'import' layers from WINS on his own platform through WMS (just like what we can do now on WINS: add a remote service, enter the URL, selected the items to import through WMS)? 

- clarification: through WMS, does part of remote content ends up being stored on UNESCO server? Or nothing at all is stored and evrything is just diplayed through a permanent )(as lonf as the link exists) data stream connecting WINS to the source of information? 
- question: Running some tests with a non-admin account, I notice that non-admin do not have the possibility to access the remote services page (http://ihp-wins-dev.geo-solutions.it/services/) which means that non-admin contributors cannot add layers through WMS. However, we need non-admin contributors to be able to add WMS layers to WINS. Please, allow non-admin users to add WMS layers. The publication process of those remote layers should follow our permission workflow 

Thank you!

**Comment by meyerch** [comment]
Dear @giohappy 

Thanks for the detailed response. 

1/ on WFS. Ok, well noted. 
2/ on WINS' WMS: thanks, this was clear. We would most probably like to discuss with you the current download process and how it could be enhanced. 
3/ on metadata/querying/etc: this was clear
4/ on permission to create new remote service: yes, we would like any contributor to be able to register a new service. Not just the Admins.

**Comment by giohappy** [comment]
Dear @meyerch 

1/ Are you willing to include upload from remote URL in our estimates for future developments?
2/ I will give you more details on this in a dedicated email
4/ Currently only superuser can do it, and it's not configurable. This is an enhancement that can be included within the estimates for future developments.
