### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#54]
If 2 users registers with same first and last name, the 2 accounts are blocked.

**Comment by meyerch** [comment]
2 persons can register with the same username (as experienced by myself). This result in the impossibility to connect (for both the users) to the platform later on, as the system retrieves 2 profiles at the same time.

When a person registers, is there a way for the system to signal that another user already has that name, hence the registering user must change her/his name? If the registering user does not alter his name, then registration should be blocked to avoid the creation of a 2nd profile with the same username.

I am suggesting this solution because we prohibited registering users to use numbers in their name.. Or can we prohibit number in the name/surname of the registration form, but allow the system to add a number at the end of the username when it has identified that it is the 2nd user with this username?

Or do you have other ideas on this? Thanks!

**Comment by afabiani** [comment]
I have implemented a first solution where if the username has already taken the system automatically adds a progressive _<num> at the end. If this works for you also we can keep it. I can manipulate the username on the backend with other rules instead of adding a number at the end if you need.

**Comment by meyerch** [comment]
That is fine with us, thanks. ACCEPTED
