### ISSUE TITLE
GeoExplorer Map Client

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#60]
Enable updated GeoExt Map Client in order to improve Layer/Map editing

**Comment by afabiani** [comment]
Can you please check the new GIS client and see if it matches your needs?

**Comment by meyerch** [comment]
I have spotted several issues. For clarity's sake, I will create 1 message per issue in this thread. Let me know if I should do otherwise

**Comment by meyerch** [comment]
1. Transparency is no longer avalaible in the viewer for layers. (issue #61 is already dedicated to this issue)

**Comment by meyerch** [comment]
2..

**Comment by meyerch** [comment]
3/ Layer switcher: there is an issue with the Humanitarian OpenStreetMap basemap. Screenshot below
![layer-switcher-osmHumanitarian.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e495832690ceba98e0ab40ac58e2d926552a5b3c09a2257991e23ab6437543434d0eee1e020a17b8eb8339a3bf6d248e590fbb873c5a76c36b11acbb821bbf00bf26895d99a4fedb1294b7607caddecd5d340c041f83fe5835a79f48c95df74fe34456b65e.PNG)

**Comment by meyerch** [comment]
4/ Print Layer/Print Preview
There is an issue with the scale in the PrintPreview [in addition to the extent-related problem stated above]
The PrintPreview opens up with a minimum, said-scale of 1:256,000,000 (1st screenshot)
![printpreview1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d9693bb8affb646b30cb2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98a4bc6eb3c2de2888748370c48.PNG)

**Comment by meyerch** [comment]
5/ Get Feature Info
Ok, it Works. 
However, since in the "Name" column of the pop-up window, there cannot be words with more than 12 characters, can you set up a fix width for the "Name" column of the Pop-up window? 
The objective is that when the user expands the pop-up window, only the "Value" column expands in width. For now, when I expand the window, both columns expand of the same width. See screenshot below: 1st screenshot is what opens up by default; 2nd is what happens when I expand the width
![GetFeature-width.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46cf918e058782bd9afbba0eb354f48021046b313916ac217586f76ae5002e580e0b4aa9450e0915f9fb8c7da6b63f708e5c0ae8d76f4d68d47f40f2ecdd42e64bef62994597b4bc804dc5e83a23e4888a4a3f1604189bb2.PNG)
![GetFeature-width-expanded.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46cf918e058782bd9afbba0eb354f480210b226b3905ad2f7581a164fd52690e050a1de853524d41f5a8dd2fa3b26a26db5909e8876d5f77c63911adbd841dad1da862da11d1e9e1d30695aa2f2ff58a87453f1b051f8ffc5e33a1984bcf58e406.PNG)

**Comment by meyerch** [comment]
6/ Layer Styles 
I am not sure to have understood/tested all the functionalities of the Layer Styles option, but so far, I have spotted some issues. 
Firstly, the pop-up window does not always look the same. It varies between layers, but also sometimes for the same layer (I open it a first time, close it, and reopen it: the LayerStyle window has changed in the meantime)
see exemple below, respectively for layers http://ihp-wins-dev.geo-solutions.it/layers/geonode:wpdxnicaragua_2017_03_15t11_17_01_last ; http://ihp-wins-dev.geo-solutions.it/layers/geonode:lacindigenous_access_to_sanitation2 ; http://ihp-wins-dev.geo-solutions.it/layers/geonode:toilet_ratio_elsalvador_female
Here, the legend is doubled in the LayerStyles window:
![style-points.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb80832f87ceb980e0b157b71fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bc8d4ac4ea3e20e28c884a2c53.PNG)
Here, I have what I believe is a normal LayerStyle window:

**Comment by afabiani** [comment]
About the OpenStreetMap tiles I guess is a temporary issue of the server. I see some tiles working

http://a.tile.openstreetmap.fr/hot/6/22/39.png

some others not working

http://a.tile.openstreetmap.fr/hot/6/23/37.png

Let's maybe wait tomorrow and see if it will work again.

**Comment by afabiani** [comment]
6/ Layer Styles - The web style editor is limited and works with SLD supported originally by GeoServer. In this case the problem is that the style contains "diamonds" which are not supported by the JavaScript library

Uncaught Error: diamond is not a valid symbol name

**Comment by afabiani** [comment]
Yes, it should work. There are still few unstabilities on GeoServer side with SLDs exported by QGIS. We need to involve Andrea Aime on this. For the moment you can try to upload the SLD and if you don't see it correctly applied, you need to go to GeoServer > Styles > <search for the style named like the layer> > <click on Apply> and refresh the GeoNode page.

**Comment by afabiani** [comment]
Hi pushed several improvements for extent, printing module and SLD update.

About the getFeatureInfo option, since the "Name" column size can be modified (see screenshot below), can we keep like this now? We can maybe open a separate issue and move to the support phase, unless this is something blocking for you.

![layer_get_feature_info](https://user-images.githubusercontent.com/1278021/31399859-f7867906-aded-11e7-8503-570df0f98835.gif)

**Comment by meyerch** [comment]
RESPONSE to 5/. 
Sorry, i missed that! Then it is fine, no worries. THanks
