### ISSUE TITLE
viewer extent - MapClient

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#65]
The viewer is still not ok from our side. 

Now that you have changed the minimum zoom available, all countries can be featured within the viewer. But the result is really not good looking, with lots of blank spaces everywhere whenever the layer needs a minimum zoom to be entirely displayed within the viewer.  

On the former version of the viewer, the layer was reapeated to form a frieze  whenever the layer was not filling up the entire space of the viewer  (screenshot below). 
![viewer-extent.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fe9d9f348791e48af1ab46aa49b2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98a44c1ee3e21e18d8a483b0c48.PNG)

We want the same thing within this viewer, to avoid having too much blank spaces around like what happens now:
![viewer-extent-new.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fe9d9f348791e48af1ab46aa49bd9a2c51653f6b14b1247a80e03cfd183954560e1aa8445c0912adfc8b2ef0b63c738a580becd46b5d66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3d2de68d8c4a3b1c011d8fed10.PNG)

**Comment by afabiani** [comment]
Currently updated the client in order to be similar to the previous one, either for Layers and Maps (old Maps should be saved again in order to apply the change)

![image](https://user-images.githubusercontent.com/1278021/31653201-07967c2c-b322-11e7-83cb-dd853155b53b.png)

Please open specific issues on how the opacity slider should work and also other on the "Anonymous" users workflow.
