### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#68]
There is an issue witht the notifications. We do receive them, but the problem is that almost every notification is received in tripli/quadriplicate or even more, which results in super crowded mailboxes.

**Comment by meyerch** [comment]
![notifications.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e69b8e2a848aaa8efdb64caa4eb2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98a44c4eb3c23e38e8b4a3c0c48.PNG)

**Comment by simboss** [comment]
hi @meyerch the standard behavior of GeoNode is to send fine grain notifications on each modifications and modifying this is not something we can do easily.

I would propose to move this issue out of Phase 1 and use some support time as  we move along to improve this behavior and then backport this improvement to  GeoNode.
One thing we might want to explore is the possibility to send batch updates (daily?, hourly?) rather than an email on each modification but again, this requires  a few days of work.

**Comment by meyerch** [comment]
Hi, 
My problem is more on the fact that  I receive the exact same notification up to 6 times every time. 
For example, I just changed the title of a map, and received the email below 6 times within the same minute. Is it normal? I feel that the notifications are duplicated everytime.

![notification.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e69b8e2a848aaa8efdb64caa1fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bc8248c9ee3f21e08c8c4d2c53.PNG)

![notification2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e69b8e2a848aaa8efdb64caa0fb2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98a44c4e13b27e18f894f3a0c48.PNG)

Other than that, the development you propose is interesting but should indeed be kept for when Phase 1 is closed.

**Comment by afabiani** [comment]
It is possible that some notifications are sent twice since intercepted by the "updated" signal. Actually it is not trivial to rebuild the notifications workflow and the idea is to revise it completely and see if there's the possibility of collecting them and avoid duplicates. This will require several hours of work and could be a good occasion to improve the whole mechanism.

**Comment by simboss** [comment]
@meyerch can you forward us a few of the emails that look duplicated?

**Comment by meyerch** [comment]
I have just forwarded you some of the notifications I received on Friday, both as an admin (Chloe.Meyer) and a regular user (contributor.test).
Let me know if you need anything else.

Sorry for the lack of reactivity on Friday, we were busy with a conference all day.

**Comment by afabiani** [comment]
We need to envisage DJango email backends modules (most probably we will need to create a custom one) able to collect messages and create digests. No good framework already existing around currently.

**Comment by giohappy** [comment]
Dear Chloe, 
did you face this issue again after WINS went into production?

**Comment by meyerch** [comment]
Dear @giohappy , 
Yes, the issue is still on the Prod instance. 

I keep receiving numerous emails of the same notification.

Below a screenshot of one notification received 9 times this morning when I edited a layer (I only made one change in the title of the layer):

![notifications.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e69b8e2a848aaa8efdb64caa4eb2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b9884fc3ee3a2de3828f4b380c48.PNG)

**Comment by giohappy** [comment]
Ok, we will do some more investigations. It doesn't appear to be WINS's fault...
